# config
[MongoDB]
DBURL = "172.26.142.156:27037"
DBName = "bridge-repo"
UserName = "bridge"
Password = "br!dge_2021092715"
Enable = false

[Chain]
BlockChain = "eth"

# swapin: eth -> ftm
[[Tokens]]
# eth: in
TxType = "swapin"
PairID = "ETH2FTM-Ethereum"
TokenAddress = "native"
DepositAddress = "0x13B432914A996b0A48695dF9B2d701edA45FF264"
Decimal=18

[[Tokens]]
# eth: out
TxType = "swapout"
PairID = "ETH2FTM-Ethereum"
TokenAddress = "native"
DepositAddress = "0x13B432914A996b0A48695dF9B2d701edA45FF264"
Decimal=18

