# config
[MongoDB]
DBURL = "172.26.142.156:27037"
DBName = "bridge-repo"
UserName = "bridge"
Password = "br!dge_2021092715"
Enable = false

[Chain]
BlockChain = "ftm"

[[Tokens]]
# mint
TxType = "swapin_2"
PairID = "ETH2FTM-USDCoin"
TokenAddress = "0x04068da6c83afcfa0e13ba15a6696662335d5b75"
DepositAddress = "0xC564EE9f21Ed8A2d8E7e76c085740d5e4c5FaFbE"
Decimals=6

# swapout: ftm -> eth
[[Tokens]]
# burn
TxType = "swapout_2"
PairID = "ETH2FTM-USDCoin"
TokenAddress = "0x04068da6c83afcfa0e13ba15a6696662335d5b75"
DepositAddress = "0xC564EE9f21Ed8A2d8E7e76c085740d5e4c5FaFbE"
Decimals=6

