# config
[MongoDB]
DBURL = "172.26.142.156:27037"
DBName = "bridge-repo"
UserName = "bridge"
Password = "br!dge_2021092715"
Enable = false

[Chain]
BlockChain = "bsc"

[[Tokens]]
# mint
TxType = "swapin_2"
PairID = "ETH2FTM-Ethereum"
TokenAddress = "0x6f817a0ce8f7640add3bc0c1c2298635043c2423"
DepositAddress = "0x13B432914A996b0A48695dF9B2d701edA45FF264"
Decimal=18

# swapout: ftm -> eth
[[Tokens]]
# burn
TxType = "swapout_2"
PairID = "ETH2FTM-Ethereum"
TokenAddress = "0x6f817a0ce8f7640add3bc0c1c2298635043c2423"
DepositAddress = "0x13B432914A996b0A48695dF9B2d701edA45FF264"
Decimal=18

